name: Quick Build Test

on:
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test-build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js 18
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: npm ci

    - name: Build Vue app
      run: npm run build

    - name: Test Electron build (Linux only)
      env:
        ELECTRON_MIRROR: https://npmmirror.com/mirrors/electron/
        ELECTRON_CACHE: ${{ github.workspace }}/.cache/electron
        ELECTRON_BUILDER_CACHE: ${{ github.workspace }}/.cache/electron-builder
      run: npm run electron:build:linux

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: quick-build-linux
        path: release/
        retention-days: 7
